### ISSUE TITLE
Tessdata access error under Windows

### ISSUE THREAD

**Issue by singsingwong2** [eihli/image-table-ocr#16] opened 2022-06-17 02:58 UTC
Hi,

I run the following demo command 

python3 -m table_ocr.demo https://raw.githubusercontent.com/eihli/image-table-ocr/master/resources/test_data/simple.png

on Windows but got the following error:

raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file C:UsersjackylamAppDataLocalPackagesPythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0LocalCachelocal-packagesPython310site-packagestable_ocrtessdata/table-ocr.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'table-ocr\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

I set TESSDATA_PREFIX and point to somewhere containing the table-ocr.traindata but no use.

However, the above problem doesn't happen on Linux. As my project prefer to run on Windows, hope someone can give me some hint on this issue. 

Thanks,
Sing

**Comment by eihli** [comment] 2022-06-23 17:49
It's probably how the code builds paths. I think it's using `/` in its path. Windows paths are `\`. The code could be made more portable by using Pythons `Path` library to build paths. If anyone creates a diff that makes that change I'd appreciatively merge it.

**Comment by rucxiaowen** [comment] 2022-06-23 17:49
你好！邮件已收到，谢谢！

**Comment by eihli** [comment] 2022-12-15 06:43
Closing this as I think it's a near-duplicate of https://github.com/eihli/image-table-ocr/issues/14

**Closed as completed by eihli** 2022-12-15 06:43 UTC
